// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SITechnicalTest.Data;

#nullable disable

namespace SITechnicalTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240304064038_create")]
    partial class create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SITechnicalTest.Models.DbSupplier", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("DbSuppliers");

                    b.HasData(
                        new
                        {
                            Name = "Supplier1",
                            CountryCode = "GB",
                            DateCreated = new DateTime(2021, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "supplier1@gmail.com"
                        },
                        new
                        {
                            Name = "Supplier2",
                            CountryCode = "JP",
                            DateCreated = new DateTime(2021, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "supplier2@gmail.com"
                        },
                        new
                        {
                            Name = "Supplier3",
                            CountryCode = "GB",
                            DateCreated = new DateTime(2021, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "supplier3@gmail.com"
                        },
                        new
                        {
                            Name = "Supplier4",
                            CountryCode = "GB",
                            DateCreated = new DateTime(2021, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "supplier4@gmail.com"
                        },
                        new
                        {
                            Name = "Supplier5",
                            CountryCode = "JP",
                            DateCreated = new DateTime(2021, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "supplier5@gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
