// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SITechnicalTest.Data;

#nullable disable

namespace SITechnicalTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SITechnicalTest.Models.DbQuotation", b =>
                {
                    b.Property<int>("QuotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuotationId"));

                    b.Property<decimal?>("CostPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("QuotationId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("SITechnicalTest.Models.DbSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "GB",
                            DateCreated = new DateTime(2021, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "supplier1@gmail.com",
                            Name = "Supplier1"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "JP",
                            DateCreated = new DateTime(2021, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "supplier2@gmail.com",
                            Name = "Supplier2"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "GB",
                            DateCreated = new DateTime(2021, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "supplier3@gmail.com",
                            Name = "Supplier3"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "GB",
                            DateCreated = new DateTime(2021, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "supplier4@gmail.com",
                            Name = "Supplier4"
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "JP",
                            DateCreated = new DateTime(2021, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "supplier5@gmail.com",
                            Name = "Supplier5"
                        });
                });

            modelBuilder.Entity("SITechnicalTest.Models.DbQuotation", b =>
                {
                    b.HasOne("SITechnicalTest.Models.DbSupplier", "Supplier")
                        .WithMany("Quotations")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SITechnicalTest.Models.DbSupplier", b =>
                {
                    b.Navigation("Quotations");
                });
#pragma warning restore 612, 618
        }
    }
}
